# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('origin', models.CharField(max_length=128)),
                ('trip', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=256)),
                ('scheduled_time', models.DateTimeField()),
                ('lateness', models.DurationField()),
                ('track', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'On Time'), (2, 'Cancelled'), (3, 'Arriving'), (4, 'End'), (5, 'Now Boarding'), (6, 'Info to Follow'), (7, 'Arrived'), (8, 'All Aboard'), (9, 'TBD'), (10, 'Departed'), (11, 'Delayed'), (12, 'Late'), (13, 'Hold')])),
            ],
        ),
    ]
