# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0002_auto_20160823_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
